export const stationList = [
  'AGTL-Agartala',
  'AGT-Agthori',
  'ALGP-Algapur',
  'ABSA-Ambasa',
  'AONI-Amoni',
  'APU-Anipur',
  'ARCL-Arunachal Junction',
  'AJRE-Aujari',
  'BPG-Badarpur Ghat',
  'BPB-Badarpur Junction',
  'BF-Bagetar',
  'BHRB-Bairabi',
  'BKS-Balikotia',
  'BXK-Bandarkhal',
  'BRLF-Bar Langfer',
  'BRHU-Barahu',
  'BRGM-Baraigram Junction',
  'BXP-Barpathar',
  'BTDR-Batadrowa Road',
  'BZGT-Bazarghat',
  'BEE-Bebejia',
  'BENA-Belonia',
  'BXG-Bhanga',
  'BHGN-Bhilgaon',
  'BHZ-Bihara',
  'BLGH-Bishalgarh',
  'BHRM-Bishramganj',
  'BXJ-Bokajan',
  'CHBN-Chandkhira Bagan',
  'CNE-Chandranathpur',
  'CPK-Chaparmukh Junction',
  'CGX-Chargola',
  'CJA-Chongajan',
  'CBZ-Churaibari',
  'DGX-Dagaon',
  'DLDE-Daldali',
  'DCA-Damchara',
  'DJA-Daotuhaja',
  'DQL-Dhalaibil',
  'DHRY-Dhalpukhuri',
  'DSR-Dhansiri',
  'DML-Dharamtul',
  'DMR-Dharmanagar',
  'DIU-Dhing',
  'DBZ-Dhing Bazar',
  'DBLG-Dibolong',
  'DGU-Digaru',
  'DKE-Dihakho',
  'DMV-Dimapur',
  'DPU-Diphu',
  'DTC-Ditokcherra',
  'DLCR-Dullabcherra',
  'ELL-Eraligul',
  'JRJE-Garjee',
  'GOE-Ghograpur',
  'GHY-Guwahati',
  'HWX-Habaipur',
  'HFG-Haflong Hill',
  'HBN-Haibargaon',
  'HKD-Hailakandi',
  'HJO-Harangajao',
  'HTL-Hatikhali',
  'HLX-Hilara',
  'HJI-Hojai',
  'JID-Jagiroad',
  'JKB-Jakhalabandha',
  'JMI-Jamguri',
  'JMRA-Jamira',
  'JMK-Jamunamukh',
  'JTG-Jatinga',
  'JGLP-Jatinga Lumpur',
  'JWNR-Jawaharnagar',
  'JRNA-Jirania',
  'JRBM-Jiribam',
  'JIGT-Jirighat',
  'JGNR-Jogendranagar',
  'JIBI-Jolaibari',
  'JGJN-Jugijan',
  'JRX-Juriagaon',
  'KQI-Kalachand',
  'KKGT-Kalkalighat',
  'KYQ-Kamakhya Junction',
  'KWM-Kampur',
  'KMNG-Kamranga',
  'KKET-Kamrup Khetri',
  'KNBR-Kanaibazar',
  'KXJ-Karimganj Junction',
  'KTX-Katakhal Junction',
  'KLCR-Katlicherra',
  'KTGM-Kayasthagram',
  'KGBP-Khongsang',
  'KHKT-Khotkhoti',
  'KUGT-Kumarghat',
  'LLBR-Lalabazar',
  'LKG-Lamsakhang',
  'LCT-Langcholiet',
  'LGT-Langting',
  'LKA-Lanka',
  'LPN-Laopani',
  'LGI-Longai',
  'LFG-Lower Haflong',
  'LMG-Lumding Junction',
  'MPRA-Mahamadpur Assam',
  'MXR-Mahur',
  'MBG-Maibang',
  'MGX-Mailongdisa',
  'MBO-Mairabari',
  'MSSN-Maishashan',
  'MYD-Manderdisa',
  'MOAR-Manipur Bagan',
  'MANU-Manu',
  'MUBR-Manu Bazar',
  'MGE-Migrendisa',
  'MRBD-Moinarband',
  'MNCR-Monacherra',
  'MGKM-Mungiakami',
  'MUPA-Mupa',
  'NPU-Nadiapur',
  'NGAN-Nagaon',
  'NLN-Nailalung',
  'NLKT-Nalkata',
  'NJN-Naojan',
  'NNGE-Narangi',
  'NHLG-New Haflong',
  'NHGJ-New Harangajao',
  'NKMG-New Karimganj Junction',
  'NSCL-New Silchar',
  'NLBR-Nilambazar',
  'OTN-Oating',
  'PNB-Panbari',
  'PNGM-Panchgram',
  'PHI-Panikhaiti',
  'PASG-Panisagar',
  'PTKD-Patharkandi',
  'PKB-Patharkhola',
  'PEC-Pencharthal',
  'PKGM-Phakhoagram',
  'PDJ-Phiding',
  'PUY-Phulaguri',
  'PUQ-Puranigudam',
  'RAHA-Raha',
  'RTRA-Ramnathpur',
  'RXR-Rangapahar',
  'RXRX-Rangapahar Crossing',
  'RGBP-Rani Gaidinliu',
  'RNGN-Ranigaon',
  'RTBR-Ratabari',
  'RUP-Rupahigaon',
  'RPB-Rupasibari',
  'SBRM-Sabroom',
  'SCA-Salchapra',
  'SLON-Salona',
  'SMGR-Samaguri',
  'STRB-Santir Bazar',
  'SZR-Sarupathar',
  'SKKE-Sekerkote',
  'SCE-Senchoa Junction',
  'SKHV-Shokhuvi',
  'SCL-Silchar',
  'SHTT-Silghat Town',
  'SKAP-SK Para',
  'SNBR-Sonuabori',
  'SIBR-Sribar',
  'SQF-Sukritipur',
  'SAKD-Suprakandi',
  'TRBE-Tarabari',
  'TLMR-Teliamura',
  'TTLA-Tetelia',
  'THTW-Thailik Twisa',
  'TKC-Thakurkuchi',
  'TGE-Thekeraguri',
  'TGBP-Thingou',
  'TBX-Tilbhum',
  'UDPU-Udaipur Tripura',
  'VNGP-Vangaichungpao',
  'WDA-Wadrengdisa',
];
